language: java
sudo: required

services:
  - docker

jdk:
  - oraclejdk8

before_install:
  - mkdir /tmp/camel-smbj
  - docker run --name smb -it -p 4139:139 -p 4445:445 -v /tmp/camel-smbj:/share -d jborza/samba-root -u "user;pass" -s "share;/share;yes;no;yes;user"

install: mvn install -DskipTests=true -Dgpg.skip=true

script: mvn verify cobertura:cobertura -Dlog4j.configuration=travis-log4j.properties

after_success:
  - bash <(curl -s https://codecov.io/bash)
